server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            logger: logger
    static_configs:
      - targets:
          - localhost
        labels:
          job: gigachat
          app: gigachat
          __path__: /var/log/gigachat/*.log

  - job_name: container_logs
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["gigachat*"]