# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Scrape configuration
scrape_configs:
  - job_name: 'gigachat'
    static_configs:
      - targets: ['localhost:8000']  # FastAPI metrics endpoint
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']  # Node exporter

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']  # Redis exporter